# https://glebbahmutov.com/blog/cypress-parallel-free/


# to use orbs, must use version >= 2.1
version: 2.1
orbs:
  cypress: cypress-io/cypress@2
workflows:
  build:
    jobs:
      - cypress/run:
          parallelism: 4
          command: npx cypress run --env split=true
