# https://filiphric.com/cypress-and-git-hub-actions-step-by-step-guide

name: e2e-tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cypress run
        uses: cypress-io/github-action@v5 # will run npm install
      - run: npx cypress run 
